workflows:
  default-workflow:
    name: FlipRush Build
    environment:
      flutter: "3.32.8"
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build Android
        script: flutter build apk --release
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - "neilogden08@gmail.com"
